### ISSUE TITLE
Отключить проверку новых версий в Google Chrome

### ISSUE THREAD

**Issue by crea7or** [crimaniak/dirty-on-steroids#95]

**Comment by crea7or** [comment]
fixed
crimaniak/dirty-on-steroids/commit/be4904a58fa67cdbed7e39294f8e02b4ebd08286

**Comment by crimaniak** [comment]
Вообще надо как-то систематизировать разруливание конфликта версий, чтобы сервис-пак из нескольких разных источников определял, что одна копия уже отработала, и избегал конфликтов.

**Comment by crea7or** [comment]
это немного другая тема. расширение само же обновляется, зачем ему проверять обновился скрипт или нет.

**Comment by Stasik0** [comment]
а что если просто добавлять в тело страницы нивидимый див с версией SP, и первым делом проверять этот див - если версия более новая - делаем return.

**Comment by crea7or** [comment]
А где гарантия, что первый успеет добавить див, а второй настолько позже стартанёт, что увидит этот див?

**Comment by Stasik0** [comment]
Юзер-скрипты точно не исполняются параллельно внутри гризманки все будет кошерно, как там с аддонами?

**Comment by crea7or** [comment]
Ничего не видел про аддоны. Да им-то пофиг, два аддона не поставится в любом случае.

**Comment by Stasik0** [comment]
Я имел ввиду один сп из аддона а второй из другого аддона (например тамперманки).
